### PR TITLE
Ensure file handle is closed using with statement

### PR DESCRIPTION
**Pull request by svisser**
This commit ensures the file is closed by using the with statement.

### CODE REVIEW

**Comment by gvalkov** [comment]
Hello. I appreciate you interest, but I'm not sure if having this in `setup.py` is of any benefit. CPython hapily closes file handles when file objects are garbage collected. Even if it didn't, it wouldn't make much of a difference for a script that is as short lived as `setup.py`.

Please reopen this issues if you disagree and have a compeling argument. Thanks.

**Comment by svisser** [comment]
You're basically saying that best practices don't apply in a short-lived script. I would disagree (as opened files always need to be closed) and hence that's why I made this pull request.

**Comment by gvalkov** [comment]
Sorry, but this is a moot point. I'm not worried about keeping a ~200 byte object in memory a little longer than absolutely necessary in a one-shot script.

**Comment by svisser** [comment]
You have a different opinion, that doesn't mean my point is moot - it just means you prefer to do things differently. I'm fine with that, it's your project after all.

**Pull request closed without merging**
